# k8s/mysql/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
  namespace: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppass
